### ISSUE TITLE
Add Endpoint to Delete Current Invitations to an Organization

### ISSUE THREAD

**Issue by JanSzyndlarewicz** [JO2K-Development/CLOCKEDIN-Backend#10]
### **Task Description**

Create an endpoint that allows administrators to delete or revoke pending invitations to join an organization. Currently, only invitation creation is possible; this endpoint should add the ability to manage or cancel these invitations. There should be sent an email informing users that the invitaiton has been canceled. (There already is a main SMTP server configured, wirte a custom function to send an email)

### **Definition of Done (DoD)**

- [ ]  An endpoint to delete pending invitations is implemented and functional.
- [ ]  The endpoint includes validation to ensure only invitations that exist and are pending can be deleted.
- [ ]  Access control confirms only administrators can perform this action.
- [ ]  The endpoint has been documented, including usage examples and possible error responses.
- [ ]  Code has passed review and is merged into the main branch without issues.

### **Resources**

- Django documentation on [generic views and APIView](https://docs.djangoproject.com/en/stable/ref/class-based-views/generic-editing/#deleteview)
- Django REST Framework class-based views
- Documentation on soft deletion or data archiving (optional, if soft delete is desired)
