### ISSUE TITLE
Create Endpoint for Retrieving and Filtering User's Working Cycles Data

### ISSUE THREAD

**Issue by JanSzyndlarewicz** [JO2K-Development/CLOCKEDIN-Backend#22]
### **Task Description**

Create an endpoint for retrieving data about working cycles saved in the `WorkingCycles` table. This endpoint should allow users to retrieve their own data. It should be a GET endpoint with filtering capabilities by various parameters (e.g., date range, etc.).

### **Definition of Done (DoD)**

- [ ] A GET endpoint is created for retrieving data from the `WorkingCycles` table.
- [ ] The endpoint allows filtering by various parameters such as date range, status, etc.
- [ ] The user can only retrieve their own working cycle data.
- [ ] Code passes review and is merged into the main branch.

### **Preferred Implementation**

Use Django REST Framework's `ModelViewSet` to handle the endpoint, with custom filters for the working cycle data. Make sure to implement appropriate permission checks to ensure users only access their own data.

### **Resources**

- [Django REST Framework Filtering Documentation](https://www.django-rest-framework.org/api-guide/filtering/)

**Comment by Apalakimmortal** [comment]
I would like to work on this issue. @JanSzyndlarewicz

**Comment by JanSzyndlarewicz** [comment]
Sure @Apalakimmortal If you have any questions feel free to contact us :)

**Comment by JanSzyndlarewicz** [comment]
@Apalakimmortal how is it going?
